version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: virtual_workspace_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    command: gunicorn virtual_workspace.wsgi:application --chdir /code/virtual_workspace --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
